### ISSUE TITLE
accumulatedNectarConcentration

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#21]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:FlowerTrait |
| **Label** | accumulatedNectarConcentration |
| **Definition** | The concentration of the nectar, in percentage of sugar, accumulated at the end of a flower lifespan which was prevented from visiting |
| **Comments** |  |
| **Examples** | `10.2`, `25` |
| **Controlled vocabulary** | |
| **Darwin Core Class** | Occurrence |
| **Cardinality** | One to many |
| **Reference Protocol** | |

**Comment by zedomel** [comment]
The actual definition of `accumulatedNectarConcentration` is: 
`The total volume in microliters of nectar accumulated at the end of a flower lifespan which was prevented from visiting`

The definition makes explicit when and how the nectar volume should be measured. Should we change it to make it more general? Maybe create a new term  for nectar volume measurements (not the accumulated volume): `nectarVolume`.

Can the accumulated nectar be calculated from a set of `nectarVolume` measurements of a particular flower, a particular plant or for the whole dataset?

**Comment by fonturbel** [comment]
Volume units missing?

**Comment by carmensspires** [comment]
@zedomel I was confused by your statements ....I think they are mixing #accumlatedNectarConcentration with #accumlatedNectarVolume....    

We can measure both (volume of nectar and concentration of sugar) during certain periods of the flower's lifetime and have, at the end, the measurement considering the entire period of the flower's life.

For me the definition of accumlatedNectarConcentration #21 está correta.

**Comment by zedomel** [comment]
Sorry @carmensspires  I posted the comment in the wrong issue :-(

But my question also applies here. The `accumulated nectar concentration` refers to the concentration as percentage of sugar of the nectar accumulated in a flower during certain period of time (it may not comprises all the flower lifespan). So, in this case the nectar is only drained from a flower once and this is what the **accumulated** means. Right? 

And what about repeatedly time measurements (not accumulated)? It looks very common in the literature people taking measurements of nectar volume and nectar concentration periodically (e.g. hourly, daily). We don't have a term for those measurements (we only have for **accumulated** nectar). So my questions are:

1) Should we add a new term `nectarConcentration` and have both `nectarConcentration` and `accumulatedNectarConcentration` (same for volume)?
2) Can we change the term `accumulatedNectarConcentration` to be more general, allowing any kind of nectar concentration measurements (accumulated or not) to be used? 

Following the options 1) and 2), after standardization, we should have something like:

| measurementID | measurementType | measurementValue | measurementDeterminedDate|
|-----:|-----:|-----:|------:|
| 1 | `nectarConcentration` | 20 | 2021-01-10 08:00|
| 2 | `nectarConcentration` | 15 | 2021-01-10 10:00|
| 3 | `nectarConcentration` | 21 | 2021-01-10 12:00|
| 4 | `nectarConcentration` | 19 | 2021-01-10 14:00|
| 5 | `nectarConcentration` | 18 | 2021-01-10 16:00|
| 6 | `accumulatedNectarConcentration` | 18 | 2021-01-10 15:00|

The measurements `1-5` are 2-hourly measurements of a particular flower of an individual and measurement `6` is a daily measurement (`accumulated`) made on another flower of the same individual. So, the `accumulated` in this example is not the `accumulated nectar concentration at the end of a flower lifespan` but a daily measurement. And so, we can have more measurements of accumulated nectar concentration for the same flower spanning for multiple days:

| measurementID | measurementType | measurementValue | measurementDeterminedDate|
|-----:|-----:|-----:|------:|
| 6 | `accumulatedNectarConcentration` | 18 | 2021-01-10 15:00|
| 7 | `accumulatedNectarConcentration` | 20 | 2021-02-10 15:00|
| 8 | `accumulatedNectarConcentration` | 21 | 2021-03-10 15:00|

So, if this kind of measurements are common, why are we fixing the **accumulated nectar concentration** measurement to be taken **only at the end of a flower lifespan**.

The definition looks for me more a definition of a **protocol** than a definition of a **measurement**. Then, I'm suggesting to change the term definition to something like:

**`The concentration, as percentage of sugar, of the accumulated nectar in a particular flower of an individual`**

This definition will comprises measurements in any period of a flower lifespan (not only at its end), also, it is not making any assumption about the number of visitations that the flower received, which makes term useful when the flower is exposed to visitors and measurements of nectar production are being made.

However, looking at the values published in the literature, we can find many studies that just publish the average (and possible the standard deviation) of the nectar concentration, what makes impossible to link measurements to particular flowers of a individual. Since, in those cases we only have a measurement of nectar concentration for multiple flowers of multiple individuals (mean + std dev), how could we link that data to a `dwc:Occurrence` (plant individual occurrence)?

In my opinion, we have to define if the measurement are reported flower-based (one measurement of each flower) or individual-based (one measurement of each individual), possibly comprises multiple flowers, which give us an average value (not so good 👎 )... or sample-based (one measurement of multiple flowers of multiple individuals), also an average value (not much informative if we don't have variances of that values).

**Comment by pjbergamo** [comment]
@zedomel Nectar is extremely variable, even among flowers of the same plant individual.
My concern here goes to allow for any kind of measurement of nectar but in the end they will not be comparable.

We now have two groups of terms for nectar: accumulated nectar - accumulated nectar and standing crop; 
1) Accumulated nectar means that flowers were bagged and no nectar was naturally removed by visitors until the measurement was made. For example, I bagged flower buds and then I measured nectar after 6h flowers were open, or after 12h flowers were open and so on. It is a surrogate of nectar production
2) Standing crop refers to a punctual nectar measurement of a flower that was open to floral visitors. It is a surrogate of nectar availability at that exact time. What you have proposed actually fits better in the standing crop terms, because for these terms it is paramount to know on which time point the measurement was made.

Accumulated nectar and standing crop are not comparable, they measure distinct processes.

For accumulated nectar, the important information is the amount of time one has let nectar accumulate AND how long flowers live (Flower longevity). This because one thing is to measure accumulated nectar after 6h in a flower that lives 6 hours (i.e. all nectar a flower can produce in its entire life) and another is to measure nectar after 6h in a flower that lives 72 hours (this flower may still produce a lot of nectar). Therefore, they are not exactly comparable.
This is quite difficult because as I said, nectar is hard to measure. What I have seen the most in the literature: accumulated nectar measurements at the end of flower lifespan OR accumulated nectar measurements at the end of the flower first day (which is more practical to measure across several species - you do not have to wait long-lived flowers accumulate nectar for several days).

My proposal actually is to add a term to make accumulated nectar comparable across species - a term to specify the amount of time that nectar has accumulated (values would be hours in integer).

**Comment by zedomel** [comment]
@pjbergamo  I got it. Thanks.

So, we have to create a new term related to `accumulatedNectarConcentration` and `accumulatedNectarVolume`, something labelled as `accumulatedNectarTime`....

Let me think little bit about it. Maybe this is the case to create **class** `NectarDynamics` (or something similar) and put all terms related to nectar measurements on that class. The class will ensure that the term are provided "together".

**Comment by anselmoeco** [comment]
In this case @zedomel, it would be important that it was also possible to specify whether the nectar accumulation time was exactly at the end of a flower lifespan, as this is a common standardization. Would adding a new term 'accumulatedNectarTime' also allow us to specify this information with an integer value (hours) of time? This reasoning should be applied to the volume and concentration of the accumulated nectar.
The definition here could be "The accumulated nectar concentration refers to the concentration as a percentage of sugar of the accumulated nectar in a flower prevented from visitors during a certain period of time (time period here may or may not be the full flower lifespan)".

**Comment by zedomel** [comment]
`dwc:measurementDeterminedDate` can be used with date-time intervals, so I think we don't need to create additional term (`nectarVolumeTime`). People can provide the amount of time they let a flower producing nectar before took the measurement by specifying an interval (it must not be specific date-time).
