### ISSUE TITLE
cospecificPollenGrainsQuantity

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-data-standard#41]
| Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Rebipp Class** | rebipp:InteractionOutcome |
| **Label** | cospecificPollenGrainsQuantity |
| **Definition** | The number or enumeration value for the quantity of coespecific pollen grains deposited on the flower's stigma(s) exposed to multiple visitors at the end of flower anthesis |
| **Comments** |  |
| **Examples** | `356`, `500` |
| **Controlled vocabulary** |  |
| **Darwin Core Class** | Event |
| **Cardinality** | One to many |
| **Reference Protocol** |  |

**Comment by zedomel** [comment]
Proposal of change the term definition to: `The quantity of coespecific pollen grains deposited on the flower's stigma(s) exposed to multiple visitors at the end of flower anthesis`.

Another issues here are about the **multiple visitors** and **at the end of flower anthesis**:

- **multiple visitors** implies multiple `Interactions`, so it is a 1-to-many relationship with `Interaction`. The term is linked to one or more `Interactions` or none at all (if the `Interaction` is not being recorded, just the coespecific pollen grains in exposed flower).

- **at the end of flower anthesis** implies that the measurement have be taken in a specific time of flower longevity. It is some kind expressing the protocol used, and not a general term for pollen grains quantity. Can we change it to be more general? How?

Additionally, which is the flower the definition is saying about? Is this a measure of the pollen grains quantity in a particular flower or a average/summarised quantity for `the flower's stigma(s)`? And what about when the flower has more than on stigma, it should be the average value? 

My suggestion is to change the term definition to make explicit the relation between the **pollen grains quantity** , a **particular flower** and the **plant Occurrence**, something like:
`The quantity of coespecific pollen grains  deposited on the stigmas(s) of a flower exposed to multiple visitors at the end of flower anthesis`.

Can we also remove the **state** and **temporal** aspects of the definition, so we have:
`The quantity of coespecific pollen grains deposited on the stigmas(s) of a flower`?

Then, with a **new term** (e.g. `flowerState`: `bagged`, `exposed`, etc.) we can capture the situation when the measurement was made. Examples:

| measureID | coespecificPollenGrainsQuantity | flowerState |
| ----- | ----- | ----- |
| 1 | 120 | `bagged`| 
| 2| 110 | `exposed`|

So, in the first row (`measureID`:`1`) we have a `single visit` situation and in the second row a `multiple visit` situation.

Also, the coespecifc pollen grains quantity is always measure **at the end of flower anthesis**? Can someone provide examples of dataset that collect that information? Any dataset with an exception to that (i.e. a coespecific pollein grains quantity taken before the end of flower anthesis)?

**Comment by fonturbel** [comment]
I agree with the definition: use only a number stating how many pollen grains were counted

**Comment by Andre-Luis-Acosta** [comment]
The term "cospecific" must be changed to "conspecific" if the meaning is correspondent to https://en.wikipedia.org/wiki/Biological_specificity#Conspecific

**Comment by zedomel** [comment]
@Andre-Luis-Acosta  thanks!

**Comment by pjbergamo** [comment]
"> Proposal of change the term definition to: `The quantity of coespecific pollen grains deposited on the flower's stigma(s) exposed to multiple visitors at the end of flower anthesis`."

Agreed.

"> * **multiple visitors** implies multiple `Interactions`, so it is a 1-to-many relationship with `Interaction`. The term is linked to one or more `Interactions` or none at all (if the `Interaction` is not being recorded, just the coespecific pollen grains in exposed flower)."

I would say that for most cases, none at all. 

"> * **at the end of flower anthesis** implies that the measurement have be taken in a specific time of flower longevity. It is some kind expressing the protocol used, and not a general term for pollen grains quantity. Can we change it to be more general? How?"

If we change it to be more general we could incur in a problem of having no comparable measurements. It is different to measure how many pollen grains were deposited in the beginning of floral longevity and in the end. Thus, we would need another term to specify the time of stigma collection (which is not I would go for). I go to keep it as it is, because the intention here is to have a measurement of the total (potential) pollen flowers could have received.

"> Additionally, which is the flower the definition is saying about? Is this a measure of the pollen grains quantity in a particular flower or a average/summarised quantity for `the flower's stigma(s)`? And what about when the flower has more than on stigma, it should be the average value?"

This can be the quantity of a particular flower. For flowers with more than one stigma, it should be the total value of the whole flower (the important information here is how many pollen grains a flower received, not that a stigma received). So this could be added as a separate sentence: For flowers with more than one stigma, present the total number of pollen grains across all stigmas (or something like this).

"> Can we also remove the **state** and **temporal** aspects of the definition, so we have:
> `The quantity of coespecific pollen grains deposited on the stigmas(s) of a flower`?"

I have exposed above my concerns.
 
"> Then, with a **new term** (e.g. `flowerState`: `bagged`, `exposed`, etc.) we can capture the situation when the measurement was made. Examples:
> 
> measureID	coespecificPollenGrainsQuantity	flowerState
> 1	120	`bagged`
> 2	110	`exposed`
> So, in the first row (`measureID`:`1`) we have a `single visit` situation and in the second row a `multiple visit` situation.""

This is what I was worried, of adding too much complexity.
Single visit and multiple visit are distinct processes. Single visit measurements are concerned on measuring the effectiveness of one pollinator species on a plant species (in other words, how many pollen grains each pollinator that interact with a flower species deposit onto stigmas). This would be a one to one relationship. We currently do not have any term for this situation, and unfortunately this data is extremely rare as it is very time consuming to obtain it.
This term was proposed only for multiple visits situation, as an overall measurement of pollination success of a flower.

"> Also, the coespecifc pollen grains quantity is always measure **at the end of flower anthesis**? Can someone provide examples of dataset that collect that information? Any dataset with an exception to that (i.e. a coespecific pollein grains quantity taken before the end of flower anthesis)?"
I am not aware of examples that have not measured pollen loads on stigmas before the end of flower anthesis.
Examples that have collected at the end of flower anthesis:

Alonso et al. 2012 https://nph.onlinelibrary.wiley.com/doi/full/10.1111/j.1469-8137.2011.03932.x
Bergamo et al. 2020 https://onlinelibrary.wiley.com/doi/full/10.1111/ele.13415?casa_token=lR4mTACXTOAAAAAA%3Aqyx2KIwn2OIQeJBcwhtV2LOoGcitunrGuoN4wVMf0kH-aD_QZ-uhcAVK2J79RnG3th4jxh8paua3HSpn

**Comment by carmensspires** [comment]
I liked the proposal to make the definition more general. I agree with the definition: The quantity of coespecific pollen grains deposited on the stigmas (s) of a flower.

**Comment by zedomel** [comment]
@pjbergamo I totally agree. I very concern about the complexity of the standard, and we should keep it much simple as possible.

So my suggestion is to keep the **temporal** and **multiple visitors** concepts here, and also, let it be a measure of a particular flower. 

I just have a comment to the sentence **multiple visitors**. When it says **multiple visitors**, it implies that this particular flower received more than one visit, but are we actually meaning that? Or the **multiple visitors** here just express the idea that the flower is **exposed** and **potentially** could receive multiple visitors? Despite, it is exposed it may receive none, one or more than on visits, or even the visitation may not being recorded (a person just collect the stigma of a flower but does not record the interactions with that particular flower). Otherwise, this term can only be filled with the person is certain that the flower really receive more than one visit, since we don't have a term for the **number of visits** for a particular flower, when we say **multiple visitors** it is just more than one, not matters how many. So why not **remove** it from the definition? 

I understand the differences between the well established practices of **single visit** and **multiple visits**. But since **single visit** implies that the flower was not exposed during all its longevity (after the first visit is bagged or has the stigma(s) collected), maybe we can change the definition to not relies on **multiple visitors** requirement.
Something like:
`A number for the quantity of conspecific pollen grains deposited on a flower's stigma(s)`
And in the **Comments** which are actually part of the standard and not just guidelines, we can add:
**Comments**: `The number of conspecific pollen grains must be measured at the end of the flower anthesis when exposed to multiple visitors`

What do you think @pjbergamo ?

**Comment by pjbergamo** [comment]
@zedomel 
Agreed!

**Comment by Andre-Luis-Acosta** [comment]
Emphasizing the use of the correct term CONespecific instead of COespecific, citing the correct use in [Bergamo et al. 2020](https://doi.org/10.1111/ele.13415)

**Comment by zedomel** [comment]
@Andre-Luis-Acosta the changes will be made when the issue is closed

**Comment by cepnunes** [comment]
To keep this term comparable among different studies and somehow keep it of general use, I suggest to change the definition to: "The quantity of conspecific pollen grains deposited on the flower's stigma(s) exposed to multiple visitors at the end in a given period of flower anthesis." That would require the addition of another field with the time during which the flower was exposed to visitors or pollinators. This time could or could not be the same of the entire flower anthesis. But it would allow the inclusion of more studies as it would not be restricted only to studies that collected after the end of anthesis.

**Comment by anselmoeco** [comment]
> @pjbergamo I totally agree. I very concern about the complexity of the standard, and we should keep it much simple as possible.
> 
> So my suggestion is to keep the **temporal** and **multiple visitors** concepts here, and also, let it be a measure of a particular flower.
> 
> I just have a comment to the sentence **multiple visitors**. When it says **multiple visitors**, it implies that this particular flower received more than one visit, but are we actually meaning that? Or the **multiple visitors** here just express the idea that the flower is **exposed** and **potentially** could receive multiple visitors? Despite, it is exposed it may receive none, one or more than on visits, or even the visitation may not being recorded (a person just collect the stigma of a flower but does not record the interactions with that particular flower). Otherwise, this term can only be filled with the person is certain that the flower really receive more than one visit, since we don't have a term for the **number of visits** for a particular flower, when we say **multiple visitors** it is just more than one, not matters how many. So why not **remove** it from the definition?
> 
> I understand the differences between the well established practices of **single visit** and **multiple visits**. But since **single visit** implies that the flower was not exposed during all its longevity (after the first visit is bagged or has the stigma(s) collected), maybe we can change the definition to not relies on **multiple visitors** requirement.
> Something like:
> `A number for the quantity of conspecific pollen grains deposited on a flower's stigma(s)`
> And in the **Comments** which are actually part of the standard and not just guidelines, we can add:
> **Comments**: `The number of conspecific pollen grains must be measured at the end of the flower anthesis when exposed to multiple visitors`
> 

I agree with this last proposition of @zedomel

**Comment by paf1306** [comment]
I agree with @pjbergamo and @zedomel to de definition "The number of conspecific pollen grains must be measured at the end of the flower anthesis when exposed to multiple visitors"

**Comment by zedomel** [comment]
**New definition**:  `A number for the quantity of conspecific pollen grains deposited on a flower's stigma(s)`
**Comments**:  `The number of conspecific pollen grains must be measured on a flower exposed to visitors at the end of the its anthesis`

@cepnunes  since the ideia at this moment is to keep the standard as much simpler as possible, adding new terms is not the best option. But, if we realize that we need this additional term it can be included in next version of the standard.
